# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/dns/config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proxy/dns/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.grpc.xray_api.common.net import destination_pb2 as common_dot_net_dot_destination__pb2
from app.grpc.xray_api.common.geodata import geodat_pb2 as common_dot_geodata_dot_geodat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proxy/dns/config.proto\x12\x0exray.proxy.dns\x1a\x1c\x63ommon/net/destination.proto\x1a\x1b\x63ommon/geodata/geodat.proto\"{\n\rDNSRuleConfig\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1a.xray.proxy.dns.RuleAction\x12\r\n\x05qtype\x18\x02 \x03(\x05\x12/\n\x06\x64omain\x18\x03 \x03(\x0b\x32\x1f.xray.common.geodata.DomainRule\"|\n\x06\x43onfig\x12\x12\n\nuser_level\x18\x01 \x01(\r\x12+\n\x04rule\x18\x02 \x03(\x0b\x32\x1d.xray.proxy.dns.DNSRuleConfig\x12\x31\n\x0erewrite_server\x18\x03 \x01(\x0b\x32\x19.xray.common.net.Endpoint*:\n\nRuleAction\x12\n\n\x06\x44irect\x10\x00\x12\x08\n\x04\x44rop\x10\x01\x12\n\n\x06Reject\x10\x02\x12\n\n\x06Hijack\x10\x03\x42L\n\x12\x63om.xray.proxy.dnsP\x01Z#github.com/xtls/xray-core/proxy/dns\xaa\x02\x0eXray.Proxy.Dnsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy.dns.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.xray.proxy.dnsP\001Z#github.com/xtls/xray-core/proxy/dns\252\002\016Xray.Proxy.Dns'
  _globals['_RULEACTION']._serialized_start=352
  _globals['_RULEACTION']._serialized_end=410
  _globals['_DNSRULECONFIG']._serialized_start=101
  _globals['_DNSRULECONFIG']._serialized_end=224
  _globals['_CONFIG']._serialized_start=226
  _globals['_CONFIG']._serialized_end=350
# @@protoc_insertion_point(module_scope)
