"""add_referrals_and_promos

Revision ID: 5127a25fe4f2
Revises: 0007_subscription_notifications
Create Date: 2026-05-30 14:18:57.508260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5127a25fe4f2'
down_revision: Union[str, None] = '0007_subscription_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('reward_days', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocodes_code'), 'promocodes', ['code'], unique=True)
    op.create_table('user_promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_promocodes_promocode_id'), 'user_promocodes', ['promocode_id'], unique=False)
    op.create_index(op.f('ix_user_promocodes_telegram_id'), 'user_promocodes', ['telegram_id'], unique=False)
    op.add_column('users', sa.Column('referrer_telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_referrer_telegram_id'), 'users', ['referrer_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referrer_telegram_id'), table_name='users')
    op.drop_column('users', 'referrer_telegram_id')
    op.drop_index(op.f('ix_user_promocodes_telegram_id'), table_name='user_promocodes')
    op.drop_index(op.f('ix_user_promocodes_promocode_id'), table_name='user_promocodes')
    op.drop_table('user_promocodes')
    op.drop_index(op.f('ix_promocodes_code'), table_name='promocodes')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
